# # -*- mode: ruby -*-
# # vi: set ft=ruby :

# Vagrant.configure("2") do |config|

#   config.vm.box = "debian/bookworm64"
#   config.vm.define "mskerbaS"
#   config.vm.hostname = "mskerbaS"
#   config.vm.network "private_network", ip: "192.168.56.110"

#   config.vm.network "forwarded_port", guest: 80, host: 8082

#   config.vm.provider "virtualbox" do |v|
#     v.name = "mskerbaS"
#     v.memory = 1024
#     v.cpus = 1
#   end

#   config.vm.provision "file", source: "./deployment", destination: "/tmp/deployment"
#   config.vm.provision "file", source: "./services", destination: "/tmp/services"
#   config.vm.provision "file", source: "./ingress/", destination: "/tmp/ingress"

  
#   config.vm.provision "shell", privileged: true, path: "script.sh"



# end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox"
end

