# Global Variables
MASTER_IP = "192.168.56.110"    # Server IP address
WORKER_IP = "192.168.56.111"    # Worker IP address
MASTER_NAME = "abouchfaS"       # Server hostname
WORKER_NAME = "abouchfaSW"      # Worker hostname

Vagrant.configure("2") do |config|
  # Server Node Configuration
  config.vm.define MASTER_NAME do |master|
    master.vm.box = "debian/bookworm64"  # latest version of Debian
    master.vm.hostname = MASTER_NAME
    master.vm.network "private_network", ip: MASTER_IP
    
    # VirtualBox-specific settings
    master.vm.provider "virtualbox" do |vb|
      vb.name = MASTER_NAME
      vb.memory = 512    # RAM allocation
      vb.cpus = 1         # CPU allocation
    end

    # Provisioning script with environment variables
    master.vm.provision "shell", path: "scripts/master.sh", env: {
      "MASTER_IP" => MASTER_IP,
      "NODE_TOKEN_FILE" => "/vagrant/node-token"
    }
  end

  # Worker Node Configuration
  config.vm.define WORKER_NAME do |worker|
    worker.vm.box = "debian/bookworm64"  # latest version of Debian
    worker.vm.hostname = WORKER_NAME
    worker.vm.network "private_network", ip: WORKER_IP
    
    worker.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
      vb.memory = 512
      vb.cpus = 1
    end

    worker.vm.provision "shell", path: "scripts/worker.sh", env: {
      "MASTER_IP" => MASTER_IP,
      "NODE_TOKEN_FILE" => "/vagrant/node-token"
    }
  end
end